---

- name: Copy Jenkins Config Files {{ jenkins_home_dir }}
  copy:
    src: jenkins/
    dest: "{{ jenkins_home_dir }}"
    group: "{{ jenkins_group }}"
    owner: "{{ jenkins_user }}"

- name: Copy Jenkins Fixed SSH Port Config {{ mapped_ssh_port }}
  template:
    src: "jenkins/org.jenkinsci.main.modules.sshd.SSHD.xml.j2"
    dest: "{{ jenkins_home_dir }}/org.jenkinsci.main.modules.sshd.SSHD.xml"
    group: "{{ jenkins_group }}"
    owner: "{{ jenkins_user }}"

- name: Copy Jenkins Docker Files (plugins)
  copy:
    src: docker/
    dest: "{{ jenkins_home_dir }}-tmp"
    group: "{{ jenkins_group }}"
    owner: "{{ jenkins_user }}"

- name: Copy Jenkins Dockerfile Template
  template:
    src: docker/Dockerfile.j2
    dest: "{{ jenkins_home_dir }}-tmp/Dockerfile"
    group: "{{ jenkins_group }}"
    owner: "{{ jenkins_user }}"
